export default [
  {
    id: 'nile-lifeline',
    name: 'Nile Lifeline',
    region: 'Cairo Region',
    description: "The Nile River has been the main source of life in Egypt for thousands of years. Ancient Egyptians depended on its annual floods to grow crops, transport goods, and build cities along its shores. Without the Nile, Egypt would mostly be desert land.",
  },
  {
    id: 'hidden-tombs',
    name: 'Hidden Tombs',
    region: 'Luxor',
    description: "The Valley of the Kings near Luxor contains dozens of royal tombs carved deep into desert cliffs. Many famous pharaohs, including Tutankhamun, were buried there with treasures and honored objects for the afterlife.",
  },
  {
    id: 'giant-temples',
    name: 'Giant Temples',
    region: 'Karnak',
    description: "The Karnak Temple Complex is one of the largest religious sites ever built. Construction continued for more than two thousand years, and different pharaohs added giant columns, statues, and honored halls to the complex.",
  },
  {
    id: 'pyramid-alignment',
    name: 'Pyramid Alignment',
    region: 'Giza',
    description: "The Great Pyramids of Giza were built with incredible precision. Historians discovered that the pyramids are closely aligned with the cardinal directions north, south, east, and west, showing the advanced knowledge of Egyptian builders.",
  },
  {
    id: 'desert-trade-routes',
    name: 'Desert Trade Routes',
    region: 'Eastern Desert',
    description: "Ancient trade routes crossed the Eastern Desert and connected Egypt with the Red Sea. Merchants transported gold, spices, stones, and other valuable resources through these dangerous desert paths.",
  },
  {
    id: 'respected-crocodiles',
    name: 'Respected Crocodiles',
    region: 'Faiyum Oasis',
    description: "In some parts of Ancient Egypt, crocodiles were considered honored animals connected with the god Sobek. Temples dedicated to Sobek existed near lakes and rivers where crocodiles lived naturally.",
  },
  {
    id: 'alexandria-library',
    name: 'Alexandria Library',
    region: 'Alexandria',
    description: "The ancient Library of Alexandria became one of the greatest centers of knowledge in the ancient world. Scholars from many countries traveled there to study science, astronomy, medicine, and philosophy.",
  },
  {
    id: 'abu-simbel-statues',
    name: 'Abu Simbel Statues',
    region: 'Aswan',
    description: "The temples of Abu Simbel are famous for their enormous statues of Ramses II carved directly into rock cliffs. The temples were later moved to higher ground to protect them from flooding after the construction of the Aswan High Dam.",
  },
  {
    id: 'white-desert-shapes',
    name: 'White Desert Shapes',
    region: 'White Desert',
    description: "The White Desert is known for unusual white rock formations shaped by wind and sand over thousands of years. Some rocks resemble animals, mushrooms, and giant sculptures rising from the desert floor.",
  },
  {
    id: 'ancient-papyrus',
    name: 'Ancient Papyrus',
    region: 'Nile Delta',
    description: "Papyrus plants growing in the Nile Delta were used by Egyptians to create one of the world’s earliest paper-like materials. Ancient scribes used papyrus sheets to record stories, laws, and religious texts.",
  },
  {
    id: 'sun-festival',
    name: 'Sun Festival',
    region: 'Abu Simbel',
    description: "Twice every year sunlight enters the inner sanctuary of the Abu Simbel temple and illuminates statues deep inside the structure. This event is connected with the architectural planning created during the reign of Ramses II.",
  },
  {
    id: 'black-desert-land',
    name: 'Black Desert Land',
    region: 'Western Desert',
    description: "Parts of the Western Desert are covered with dark volcanic stones that give the landscape its black appearance. These unusual formations were created by ancient volcanic activity thousands of years ago.",
  },
  {
    id: 'cleopatras-port',
    name: "Cleopatra’s Port",
    region: 'Alexandria',
    description: "Archaeologists discovered remains of ancient buildings and statues underwater near Alexandria. Some historians believe these ruins belonged to parts of Cleopatra’s royal palace and harbor district.",
  },
  {
    id: 'temple-colors',
    name: 'Temple Colors',
    region: 'Edfu',
    description: "Many Egyptian temples originally contained bright colors painted across columns, walls, and statues. Small traces of red, blue, and yellow paint can still be seen today inside some ancient structures.",
  },
  {
    id: 'cat-guardians',
    name: 'Cat Guardians',
    region: 'Bubastis',
    description: "Cats were highly respected in Ancient Egypt and were associated with the goddess Bastet. In the city of Bubastis large celebrations honored cats and the protective powers connected with them.",
  },
  {
    id: 'desert-monasteries',
    name: 'Desert Monasteries',
    region: 'Sinai Peninsula',
    description: "The Sinai region contains some of the oldest Christian monasteries in the world. Monks built isolated religious communities in the mountains and deserts to live peaceful spiritual lives.",
  },
  {
    id: 'stone-obelisks',
    name: 'Stone Obelisks',
    region: 'Aswan',
    description: "Ancient Egyptian obelisks were carved from giant pieces of granite taken from quarries in Aswan. Workers used stone tools and incredible precision to shape these massive monuments.",
  },
  {
    id: 'ancient-lighthouse',
    name: 'Ancient Lighthouse',
    region: 'Alexandria',
    description: "The Lighthouse of Alexandria, also called the Pharos, was once one of the tallest structures in the ancient world. It guided ships safely into the harbor and became one of the Seven Wonders of the Ancient World.",
  },
  {
    id: 'desert-fossils',
    name: 'Desert Fossils',
    region: 'Wadi Al-Hitan',
    description: "Wadi Al-Hitan, also known as the Valley of the Whales, contains fossils of ancient whales that lived millions of years ago when the region was covered by sea water.",
  },
  {
    id: 'golden-tomb-masks',
    name: 'Golden Tomb Masks',
    region: 'Luxor',
    description: "Egyptian craftsmen created detailed golden masks for royal burials. The mask of Tutankhamun became one of the most famous artifacts in history because of its artistic detail and preserved condition.",
  },
];