// ...existing code...
export default [
  {
    id: 'karnak-temple',
    name: 'Karnak Temple',
    category: 'Ancient Temples',
    coords: { lat: 25.7188, lng: 32.6573 },
    description: 'Karnak Temple in Luxor is one of the largest religious complexes ever built, famous for the Great Hypostyle Hall with enormous pillars and hieroglyphics.',
    image: require('../thosiganems/KarnakTemple.png'),
  },
  {
    id: 'luxor-temple',
    name: 'Luxor Temple',
    category: 'Ancient Temples',
    coords: { lat: 25.6996, lng: 32.6396 },
    description: 'Luxor Temple was constructed mainly under Amenhotep III and Ramses II and is dedicated to the renewal of kingship, noted for massive statues and reliefs.',
    image: require('../thosiganems/LuxorTemple.png'),
  },
  {
    id: 'abu-simbel-temples',
    name: 'Abu Simbel Temples',
    category: 'Ancient Temples',
    coords: { lat: 22.3372, lng: 31.6258 },
    description: 'Carved into rock cliffs under Ramses II, Abu Simbel is guarded by four colossal statues and was famously relocated to avoid flooding from the Aswan Dam.',
    image: require('../thosiganems/AbuSimbelTemples.png'),
  },
  {
    id: 'temple-of-philae',
    name: 'Temple of Philae',
    category: 'Ancient Temples',
    coords: { lat: 24.0258, lng: 32.8849 },
    description: 'Located on Agilkia Island near Aswan, the Temple of Philae was dedicated to Isis and was moved to protect it from rising Nile waters.',
    image: require('../thosiganems/TempleofPhilae.png'),
  },
  {
    id: 'temple-of-edfu',
    name: 'Temple of Edfu',
    category: 'Ancient Temples',
    coords: { lat: 24.9779, lng: 32.8740 },
    description: 'The Temple of Edfu is one of the best-preserved Egyptian temples, dedicated to a sky-guardian deity with detailed carvings and Ptolemaic-period reliefs.',
    image: require('../thosiganems/TempleofEdfu.png'),
  },
  {
    id: 'temple-of-hathor',
    name: 'Temple of Hathor',
    category: 'Ancient Temples',
    coords: { lat: 26.1433, lng: 32.6733 },
    description: 'The Dendera Temple of Hathor is known for its decorated ceilings, astronomical carvings, and traces of original interior colors.',
    image: require('../thosiganems/TempleofHathor.png'),
  },

  {
    id: 'tomb-of-tutankhamun',
    name: 'Tomb of Tutankhamun',
    category: 'Pharaoh Tombs',
    coords: { lat: 25.7402, lng: 32.6014 },
    description: 'Discovered by Howard Carter in 1922 nearly intact, Tutankhamun’s tomb contained golden treasures and the famous funerary mask.',
    image: require('../thosiganems/TombofTutankhamun.png'),
  },
  {
    id: 'tomb-of-ramses-vi',
    name: 'Tomb of Ramses VI',
    category: 'Pharaoh Tombs',
    coords: { lat: 25.7405, lng: 32.6018 },
    description: 'The Tomb of Ramses VI is noted for long decorated corridors and colorful ceiling scenes from Egyptian mythology and the afterlife.',
    image: require('../thosiganems/TombofRamsesVI.png'),
  },
  {
    id: 'tomb-of-seti-i',
    name: 'Tomb of Seti I',
    category: 'Pharaoh Tombs',
    coords: { lat: 25.7409, lng: 32.6020 },
    description: 'Considered one of the most beautifully decorated tombs, Seti I’s burial contains finely preserved carvings and painted walls.',
    image: require('../thosiganems/TombofSetiI.png'),
  },
  {
    id: 'tomb-of-nefertari',
    name: 'Tomb of Nefertari',
    category: 'Pharaoh Tombs',
    coords: { lat: 25.7276, lng: 32.6010 },
    description: 'The Tomb of Nefertari is famed for its vibrant wall paintings and elegant artwork depicting the queen’s journey through the afterlife.',
    image: require('../thosiganems/TombofNefertari.png'),
  },
  {
    id: 'tomb-of-thutmose-iii',
    name: 'Tomb of Thutmose III',
    category: 'Pharaoh Tombs',
    coords: { lat: 25.7423, lng: 32.6035 },
    description: 'The tomb of Thutmose III contains unique artistic styles and religious texts reflecting the pharaoh’s military and cultural prominence.',
    image: require('../thosiganems/TombofThutmoseIII.png'),
  },
  {
    id: 'tomb-of-amenhotep-ii',
    name: 'Tomb of Amenhotep II',
    category: 'Pharaoh Tombs',
    coords: { lat: 25.7415, lng: 32.6028 },
    description: 'Important for archaeological discoveries, Amenhotep II’s tomb includes painted corridors, ritual texts, and scenes of burial traditions.',
    image: require('../thosiganems/TombofAmenhotepII.png'),
  },

  {
    id: 'pyramid-of-djoser',
    name: 'Pyramid of Djoser',
    category: 'Desert Ruins',
    coords: { lat: 29.8713, lng: 31.2165 },
    description: 'The Pyramid of Djoser at Saqqara is the world’s first large stone pyramid, introducing the step-pyramid design of the Third Dynasty.',
    image: require('../thosiganems/PyramidofDjoser.png'),
  },
  {
    id: 'great-sphinx-of-giza',
    name: 'Great Sphinx of Giza',
    category: 'Desert Ruins',
    coords: { lat: 29.9753, lng: 31.1376 },
    description: 'The Great Sphinx, with a lion’s body and a pharaoh’s head, is a monumental limestone guardian symbolizing royal strength near the Giza pyramids.',
    image: require('../thosiganems/GreatSphinxofGiza.png'),
  },
  {
    id: 'roman-ruins-of-kellis',
    name: 'Roman Ruins of Kellis',
    category: 'Desert Ruins',
    coords: { lat: 25.4928, lng: 28.9792 },
    description: 'Kellis in the Dakhla Oasis reveals houses, temples, churches, and manuscripts that illuminate daily life in Roman-era Egypt.',
    image: require('../thosiganems/RomanRuinsofKellis.png'),
  },
  {
    id: 'amarna-ruins',
    name: 'Amarna Ruins',
    category: 'Desert Ruins',
    coords: { lat: 27.6463, lng: 30.8947 },
    description: 'Amarna, the capital of Akhenaten, contains temple and palace remains from a unique religious period in Egyptian history.',
    image: require('../thosiganems/AmarnaRuins.png'),
  },
  {
    id: 'temple-ruins-of-tanis',
    name: 'Temple Ruins of Tanis',
    category: 'Desert Ruins',
    coords: { lat: 30.9639, lng: 31.8733 },
    description: 'Tanis was a major Nile Delta city with broken statues, obelisks, and temple remains tied to later Egyptian dynasties.',
    image: require('../thosiganems/TempleRuinsofTanis.png'),
  },
  {
    id: 'fortress-of-babylon',
    name: 'Fortress of Babylon',
    category: 'Desert Ruins',
    coords: { lat: 30.0062, lng: 31.2303 },
    description: 'The Fortress of Babylon in Old Cairo, built during Roman rule, remains significant for its surviving towers and defensive structures.',
    image: require('../thosiganems/FortressofBabylon.png'),
  },
];